// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tutorial

import (
	"database/sql"
)

type BookInfo struct {
	ID      string
	Asin    sql.NullString
	Guid    sql.NullString
	Lang    sql.NullString
	Title   sql.NullString
	Authors sql.NullString
}

type Lookup struct {
	ID        string
	WordKey   sql.NullString
	BookKey   sql.NullString
	DictKey   sql.NullString
	Pos       sql.NullString
	Usage     sql.NullString
	Timestamp sql.NullInt64
}

type Word struct {
	ID        string
	Word      sql.NullString
	Stem      sql.NullString
	Lang      sql.NullString
	Category  sql.NullInt64
	Timestamp sql.NullInt64
	Profileid sql.NullString
}
